### ISSUE TITLE
Get variable type for message variables

### ISSUE THREAD

**Issue by LokiMidgard** [blushingpenguin/Fluent.Net#5]
Is there any way to interfere the type of a variable in the message?

I've looked at the specs but I didn't find anything. I had two ideas:
1. look if an variable will be used with an variant called [one], [many],...
    But i think those will also match if a string `one` will be suplyed instead of an number.
2. look at the comments. The comments in the documentation samples have a simular pattern 
```
# $duration (Number) - The duration in seconds.
time-elapsed = Time elapsed: { $duration }s.
```
With variable name followed by the type in parenthise followed by the description of the parameter.

-----------------------------------------------------------------

*background*  
I'm writing an generator simular to the resx generator, which will create a boilerpate code to accesss your lib. That way you always see all messages and what variables need to be provided.

**Comment by blushingpenguin** [comment]
The one, many variants are actually handled by pluralization rules - different languages have different rules for what consititutes one, two, many, etc - see [https://projectfluent.org/fluent/guide/selectors.html](https://projectfluent.org/fluent/guide/selectors.html)

I'm not really sure why you need to know the variable type within the message definition -- isn't it implicit from the context of the message?  Could you expand on why you need the variable type?

**Comment by LokiMidgard** [comment]
Well, I like strongly typed stuff. And when I generate wrapers, I would prefere to show the type for every parameter. so when I generate the sharedPhotos sample from the fulent site my code will generate following
```
var seccondString = TestFtl.SharedPhotos[userName:"Bob", photoCount:3, userGender:"male"];
```

And I would like to have the generated code use the types `string` for userName and userGender, and `int` for photoCount. instead of `object` for everything.

I've also sought of somehow generating enums e.g for userGender.

**Comment by blushingpenguin** [comment]
Then I guess parsing the comments would make sense in the generator.  If you use the AST parser rather than the runtime parser the comments will be retained.  Otherwise you are just looking at a VariableReference and there's no clue in the fluent syntax as to the type of the variable.

The only other way I can think of achieving what you want is to encode the type of the variable in the variable reference itself, then drop it in the generated code, e.g.

foo = Dear { $strUserName }, you have { $numPhotoCount }; gender = { $possibleEnumUserGender }

That would be easier to code than parsing the comment text and trying to match the names up.

**Comment by LokiMidgard** [comment]
Thakn you.

I think I stick to the comments. I already tested that with an [regex](https://github.com/LokiMidgard/Fluent.Generator/blob/23ac37405686a8aee9aef6c568cf2ce2420c541b/Fluent.Generator/Generator.cs#L217). The only downside is it can easely break if someone make typing errors. 

I think I currently make a fallback to `object` in that case. It is propably better to generate buld errors instead.
